### ISSUE TITLE
Default boolean property value in the C# DTO will always be used instead of the passed value

### ISSUE THREAD

**Issue by mayerwin** [ServiceStackApps/typescript-react-template#3]
I am encountering the following weird behavior. I updated the `Hello.cs` DTO class to the following, adding a "Happy" boolean property and C# 6 default values for both properties:

```
[Route("/hello/{Name}")]
public class Hello : IReturn<HelloResponse> {
    public string Name { get; set; } = "Default name";
    public bool Happy { get; set; } = true;
}

public class HelloResponse {
    public string Result { get; set; }
}
```

In `hello.tsx`, I have changed the `update` function to the following:

```
update(event: any) {
    var request = new Hello();
    request.Name = event.target.value;
    request.Happy = false;
    this.client.get(request).then((helloResponse) => {
        this.setState({
            msg: helloResponse.Result
        });
    });
}
```

Now, in `MyServices.cs`, upon receiving the DTO, `request.Happy` will be equal to true even if it has been set to false in TypeScript! 
This issue doesn't happen for the `Name` string property, nor when the default property for `Happy` is set to false.
Is it a bug? I am using the latest ServiceStack version.

**Comment by mythz** [comment]
The issue is due to specifying default values in your DTOs - which is just sugar for having a constructor implementation populating each property. DTOs should only define your Service Contract, they shouldn't have any implementation or behavior as they wont be available in any tool that generates service clients like [Add ServiceStack Reference](http://docs.servicestack.net/add-servicestack-reference) as only the structure of the DTOs are generated, none of its implementation - which shouldn't be in DTOs as your clients are going to have different behavior depending on if they're using your **ServiceModel.dll** (which contains your impl) vs generated the DTOs using a tool (which wont).

The `JsonServiceClient` isn't sending a value for default value of `false` so when the Request DTO is populated it's not overriding the default **true** value in your `Hello` Request DTO. A lot of serializers aren't going to send default values to reduce the wire payload as it's expected DTOs are naturally going to be populated with its default(T) value which is incompatible with your use of custom Default values. 

There might be a case for special casing boolean types and always sending `true` or `false` values but I prefer not to include different rules for different types if I can help it.

**Comment by mythz** [comment]
I've changed the behavior of **servicestack-client** to always send non-null/undefined values in [this commit](https://github.com/ServiceStack/servicestack-client/commit/ba239075c7f3f914098fc2ae7b639e005165d526) which is available from **v0.0.12** that's now on npm so if you update to the latest version of [servicestack-client](https://www.npmjs.com/package/servicestack-client) it will now send default values.

Although I still recommend removing default values from your DTOs as per above.

**Comment by mayerwin** [comment]
Great, thanks for the update. I agree that it is not a good idea to encode default values in DTO. I had only done it to auto initialize some properties from C#, knowing I would have to set them manually in TypeScript. But further down the road, having two different DTO implementations (one with default value and the other without) can definitely lead to dangerously wrongful assumptions.

On a non related note, I recently found out about this quite interesting project: http://bridge.net/. I thought I would mention it in case you had not come across it yet. A good tool to be aware of, though I found the React implementations in C# to be quite verbose compared to JSX.

**Comment by mythz** [comment]
Nope haven't come across it but have seen many attempts at compiling C# in the past which have all failed, either producing heavy, verbose and ugly code or invalid C# semantics. IMO TypeScript is the right strategy for transpiling to JS, add Types and benefit from compiler type feedback and tooling support + let you use future ES6/7 features by targeting to down-level browsers without trying to change JS semantics so it's easy to leverage the existing js ecosystem.

The only C# -> JS VM strategy I think is viable is if it compiles down to WASM.
